export const accounts = [
  {
    id: "acc_1",
    name: "Main Checking",
    bank: "Chase Bank",
    type: "checking",
    balance: 12850.94,
    number: "**** 4149",
    color: "from-emerald-500 to-emerald-700",
    income: 5400,
    expenses: 3210,
  },
  {
    id: "acc_3",
    name: "Investment Portfolio",
    bank: "Fidelity",
    type: "investment",
    balance: 47902.79,
    number: "**** 3301",
    color: "from-amber-500 to-amber-700",
    income: 1200,
    expenses: 450,
  },
];

export const totalBalance = accounts.reduce((sum, a) => sum + a.balance, 0);

export const expenseBreakdown = [
  { category: "Housing", amount: 1800, color: "#10b981", pct: 38 },
  { category: "Food & Dining", amount: 640, color: "#f59e0b", pct: 14 },
  { category: "Transport", amount: 420, color: "#3b82f6", pct: 9 },
  { category: "Subscriptions", amount: 180, color: "#8b5cf6", pct: 4 },
  { category: "Healthcare", amount: 310, color: "#ef4444", pct: 7 },
  { category: "Entertainment", amount: 260, color: "#06b6d4", pct: 6 },
  { category: "Others", amount: 600, color: "#6b7280", pct: 13 },
];

export const cashFlowData = [
  { month: "Jan", income: 5400, expenses: 3100 },
  { month: "Feb", income: 5400, expenses: 3400 },
  { month: "Mar", income: 6200, expenses: 3210 },
  { month: "Apr", income: 5400, expenses: 2900 },
  { month: "May", income: 7100, expenses: 3600 },
  { month: "Jun", income: 5400, expenses: 3210 },
];

export const pendingPayments = [
  {
    id: "pay_1",
    name: "Rent Payment",
    recipient: "Greenwood Properties",
    amount: 1800,
    dueDate: "2026-05-15",
    status: "overdue",
    category: "Housing",
    accountId: "acc_1",
  },
  {
    id: "pay_2",
    name: "Netflix Subscription",
    recipient: "Netflix Inc.",
    amount: 15.99,
    dueDate: "2026-05-10",
    status: "upcoming",
    category: "Subscriptions",
    accountId: "acc_1",
  },
  {
    id: "pay_3",
    name: "Electric Bill",
    recipient: "City Power & Light",
    amount: 134.5,
    dueDate: "2026-05-12",
    status: "upcoming",
    category: "Utilities",
    accountId: "acc_1",
  },
  {
    id: "pay_4",
    name: "Car Insurance",
    recipient: "State Farm",
    amount: 210.0,
    dueDate: "2026-05-20",
    status: "scheduled",
    category: "Insurance",
    accountId: "acc_2",
  },
  {
    id: "pay_5",
    name: "Internet Plan",
    recipient: "Comcast",
    amount: 79.99,
    dueDate: "2026-05-08",
    status: "overdue",
    category: "Subscriptions",
    accountId: "acc_1",
  },
  {
    id: "pay_6",
    name: "Gym Membership",
    recipient: "FitLife Gym",
    amount: 49.99,
    dueDate: "2026-05-25",
    status: "scheduled",
    category: "Health",
    accountId: "acc_1",
  },
];

export const budgets = [
  {
    id: "bud_1",
    category: "Housing",
    allocated: 2000,
    spent: 1800,
    accountId: "acc_1",
    color: "#10b981",
  },
  {
    id: "bud_2",
    category: "Food & Dining",
    allocated: 800,
    spent: 640,
    accountId: "acc_1",
    color: "#f59e0b",
  },
  {
    id: "bud_3",
    category: "Transport",
    allocated: 500,
    spent: 420,
    accountId: "acc_1",
    color: "#3b82f6",
  },
  {
    id: "bud_4",
    category: "Healthcare",
    allocated: 400,
    spent: 310,
    accountId: "acc_1",
    color: "#ef4444",
  },
  {
    id: "bud_5",
    category: "Entertainment",
    allocated: 300,
    spent: 260,
    accountId: "acc_1",
    color: "#8b5cf6",
  },
  {
    id: "bud_6",
    category: "Subscriptions",
    allocated: 200,
    spent: 180,
    accountId: "acc_1",
    color: "#06b6d4",
  },
  {
    id: "bud_7",
    category: "Savings",
    allocated: 1000,
    spent: 800,
    accountId: "acc_2",
    color: "#10b981",
  },
  {
    id: "bud_8",
    category: "Investments",
    allocated: 2000,
    spent: 1650,
    accountId: "acc_3",
    color: "#f59e0b",
  },
];

export const recentTransactions = [
  {
    id: "txn_1",
    name: "Design Service",
    counterparty: "Erick White",
    amount: -299,
    date: "May 6, 2026",
    type: "expense",
    category: "Services",
  },
  {
    id: "txn_2",
    name: "Freelance Payment",
    counterparty: "Ann Smith",
    amount: 4599,
    date: "May 5, 2026",
    type: "income",
    category: "Income",
  },
  {
    id: "txn_3",
    name: "Rental Income",
    counterparty: "John Doe",
    amount: 1800,
    date: "May 4, 2026",
    type: "income",
    category: "Income",
  },
  {
    id: "txn_4",
    name: "Spotify Premium",
    counterparty: "Spotify AB",
    amount: -9.99,
    date: "May 3, 2026",
    type: "expense",
    category: "Subscriptions",
  },
  {
    id: "txn_5",
    name: "Grocery Run",
    counterparty: "Whole Foods",
    amount: -87.4,
    date: "May 2, 2026",
    type: "expense",
    category: "Food",
  },
];
